allowedDeprecatedVersions:
  "@npmcli/move-file": "3.0.0"
  "boolean": "^3.2.0"
  "gar": "^1.0.4"
  "glob": "8.1.0"
  "inflight": "1.0.6"
  "lodash.get": "^4.4.2"

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild

overrides:
  "@npmcli/move-file": "3.0.0"
  "@electron/fuses": "2.0.0"
  esbuild: ">=0.27.1"
  "glob": "8.1.0"
  "rimraf": "^6.1.2"
  tmp: ">=0.2.4"
